from __future__ import annotations

import os
import tempfile
from pathlib import Path

from .corpus import (
    AXES,
    Corpus,
    CorpusError,
    ResearchRecord,
    assert_no_redirecting_ancestors,
    assert_plain_contained_path,
    load_corpus,
)


GENERATED_MARKER = "<!-- generated by research-corpus/scripts/research.py; do not edit -->"
AXIS_VIEW = {
    "domains": ("by-domain", "By domain", "domain"),
    "mechanisms": ("by-mechanism", "By mechanism", "mechanism"),
    "qualities": ("by-quality", "By quality", "quality"),
    "platforms": ("by-platform", "By platform", "platform"),
}


def _front_matter(nav: list[str]) -> str:
    if not nav:
        return "---\nnav: []\n---\n"
    return "---\nnav:\n" + "".join(f"  - {item}\n" for item in nav) + "---\n"


def _record_link(record: ResearchRecord, prefix: str) -> str:
    return f"[{record.title}]({prefix}{record.id}.md)"


def _short_revision(kind: str, value: str) -> str:
    return value[:12] if kind == "git-commit" else value.removeprefix("sha256:")[:12]


PROVENANCE_START = "<!-- research:provenance -->"
PROVENANCE_END = "<!-- /research:provenance -->"


def _verified_date(record: ResearchRecord) -> str:
    # A new draft has a required date field, but has not established evidence.
    return "Not reviewed (draft)" if record.status == "draft" else record.verified_at


def _provenance_block(record: ResearchRecord, corpus: Corpus) -> str:
    """The evidence a reader must see before trusting a record.

    A record's sources, their exact revisions, and its dates live in machine
    front matter, which the site strips. Without this block a published record
    reads as unattributed prose: no source, no commit, no date. The block is
    generated from that same front matter, so the two cannot drift.
    """

    lines = [
        PROVENANCE_START,
        "",
        f"**Written** {written_on(record) or 'unknown'} · "
        f"**Evidence last verified** {_verified_date(record)} · "
        f"**Status** `{record.status}` · **Kind** `{record.kind}`",
        "",
        "<!-- table-columns: 25% 10% 40% 25% -->",
        "| Source | Role | Revision cited by this record | Snapshot taken |",
        "|---|---|---|---|",
    ]
    for source in record.sources:
        catalog = corpus.sources[source["id"]]
        name = catalog.name.replace("|", "\\|")
        label = f"[{name}]({catalog.url})" if catalog.url else name
        revision = source["revision"]
        cited = f"`{revision['kind']}:{revision['value']}`"
        captured = (catalog.retrieved_at if revision == catalog.revision.as_dict()
                    else "Not recorded for this historical revision")
        if revision != catalog.revision.as_dict() and catalog.kind != "local-repository":
            cited += " — the catalog has since moved; re-read before citing"
        lines.append(
            f"| {label}<br><small>`{catalog.id}`</small> | {source['role']} | {cited} "
            f"| {captured} |"
        )
    lines += [
        "",
        "Every observation below names one of these sources and an exact locator inside it.",
        "",
        PROVENANCE_END,
    ]
    return "\n".join(lines)


def _record_with_provenance(text: str, block: str) -> str:
    """Insert or replace the generated provenance block just under the title."""

    start = text.find(PROVENANCE_START)
    end = text.find(PROVENANCE_END)
    if start != -1 and end != -1 and end > start:
        return text[:start] + block + text[end + len(PROVENANCE_END):]
    if start != -1 or end != -1:
        raise CorpusError("a research record carries only one provenance marker")
    marker = "\n# "
    heading = text.find(marker)
    if heading == -1:
        raise CorpusError("a research record has no title heading to place provenance under")
    line_end = text.find("\n", heading + len(marker))
    if line_end == -1:
        raise CorpusError("a research record's title heading is unterminated")
    return text[: line_end + 1] + "\n" + block + "\n" + text[line_end + 1 :]


def expected_record_provenance(corpus: Corpus) -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for record in corpus.records.values():
        _assert_safe_projection_path(corpus, record.path)
        text = record.path.read_text(encoding="utf-8")
        updated = _record_with_provenance(text, _provenance_block(record, corpus))
        if updated != text:
            expected[record.path] = updated
    return expected


def written_on(record: ResearchRecord) -> str:
    """The date in the record id, which is the date the record was written."""

    parts = record.id.split("-")
    return "-".join(parts[1:4]) if len(parts) > 4 else ""


def _records_index(corpus: Corpus) -> str:
    # Newest first: the question a reader arrives with is almost always "what
    # has been studied lately", and a title-sorted list answers a different one.
    by_recency = sorted(
        corpus.records.values(),
        key=lambda item: (written_on(item), item.verified_at, item.id),
        reverse=True,
    )
    body = [
        _front_matter([f"{record.id}.md" for record in by_recency]),
        GENERATED_MARKER,
        "\n# Research records\n\n",
    ]
    if not by_recency:
        body.append(
            "No research records have been published yet. Add a canonical record, then "
            "regenerate navigation and taxonomy views.\n"
        )
        return "".join(body)

    body.append(
        "Newest first. Each record has one stable location; taxonomy and source pages link "
        "here and never copy it. **Written** is when the record was authored, **verified** "
        "when its evidence was last re-read against the cited revisions — an old verified "
        "date on a live source is the signal to re-check before citing.\n\n"
    )
    body.append("<!-- table-columns: 40% 10% 10% 15% 25% -->\n")
    body.append("| Record | Kind | Status | Written | Verified |\n|---|---|---|---|---|\n")
    for record in by_recency:
        body.append(
            f"| {_record_link(record, '')} | `{record.kind}` | `{record.status}` | "
            f"{written_on(record)} | {_verified_date(record)} |\n"
        )
    stale = [record for record in by_recency if record.health]
    if stale:
        body.append(
            f"\n{len(stale)} record(s) cite a revision that has since moved; open one to see "
            "which source, and re-read the evidence before relying on it.\n"
        )
    return "".join(body)


def _taxonomy_axis_page(corpus: Corpus, axis: str, used: dict[str, list[ResearchRecord]]) -> str:
    directory, title, singular = AXIS_VIEW[axis]
    del directory
    nav = [f"{value}/" for value in sorted(used)]
    body = [
        _front_matter(nav),
        GENERATED_MARKER,
        f"\n# {title}\n\n",
        "This vocabulary is canonical; directories appear only for values used by at least "
        "one research record.\n\n",
        "| Value | Meaning | Records |\n",
        "| --- | --- | ---: |\n",
    ]
    for value, term in sorted(corpus.taxonomy.axes[axis].items()):
        count = len(used.get(value, ()))
        value_cell = f"[{value}]({value}/)" if count else f"`{value}`"
        body.append(f"| {value_cell} | {term.label} | {count} |\n")
    if not corpus.taxonomy.axes[axis]:
        body.append(f"\nNo {singular} vocabulary has been declared.\n")
    return "".join(body)


def _leaf_page(title: str, description: str, records: list[ResearchRecord]) -> str:
    body = [
        _front_matter([]),
        GENERATED_MARKER,
        f"\n# {title}\n\n",
        f"{description}\n\n",
    ]
    for record in sorted(records, key=lambda item: (item.title.casefold(), item.id)):
        health = ", ".join(record.health) if record.health else "current source revisions"
        body.append(
            f"- {_record_link(record, '../../../records/')} — `{record.kind}` / "
            f"`{record.status}` / {health}\n"
        )
    return "".join(body)


def _source_index(corpus: Corpus, used: dict[str, list[ResearchRecord]]) -> str:
    body = [
        _front_matter([f"{source_id}/" for source_id in sorted(used)]),
        GENERATED_MARKER,
        "\n# By source\n\n",
        "Source directories appear when at least one research record cites the pinned source.\n\n",
        "| Source | Kind | Revision | Records |\n",
        "| --- | --- | --- | ---: |\n",
    ]
    for source_id, source in sorted(corpus.sources.items()):
        count = len(used.get(source_id, ()))
        cell = f"[{source.name}]({source_id}/)" if count else source.name
        revision = _short_revision(source.revision.kind, source.revision.value)
        body.append(
            f"| {cell} (`{source_id}`) | `{source.kind}` | "
            f"`{source.revision.kind}:{revision}` | {count} |\n"
        )
    return "".join(body)


def _status_index(used: dict[str, list[ResearchRecord]]) -> str:
    statuses = ("draft", "reviewed", "superseded", "retired")
    body = [
        _front_matter([f"{status}/" for status in statuses if used.get(status)]),
        GENERATED_MARKER,
        "\n# By status\n\n",
        "Author-declared lifecycle status is separate from derived source health.\n\n",
        "| Status | Records |\n",
        "| --- | ---: |\n",
    ]
    for status in statuses:
        count = len(used.get(status, ()))
        cell = f"[{status}]({status}/)" if count else f"`{status}`"
        body.append(f"| {cell} | {count} |\n")
    return "".join(body)


def expected_views(corpus: Corpus) -> dict[Path, str]:
    docs = corpus.paths.docs
    expected: dict[Path, str] = {docs / "records" / "_index.md": _records_index(corpus)}
    root_nav = [
        "by-domain/",
        "by-mechanism/",
        "by-quality/",
        "by-platform/",
        "by-source/",
        "by-status/",
    ]
    expected[docs / "views" / "_index.md"] = "".join(
        (
            _front_matter(root_nav),
            GENERATED_MARKER,
            "\n# Research views\n\n",
            "These pages are disposable projections of canonical research records. Regenerate "
            "them after editing records, source identities, or taxonomy; never place unique "
            "knowledge here.\n",
        )
    )

    for axis in AXES:
        directory, title, singular = AXIS_VIEW[axis]
        used: dict[str, list[ResearchRecord]] = {}
        for record in corpus.records.values():
            for value in record.facets[axis]:
                used.setdefault(value, []).append(record)
        expected[docs / "views" / directory / "_index.md"] = _taxonomy_axis_page(
            corpus, axis, used
        )
        for value, records in used.items():
            term = corpus.taxonomy.axes[axis][value]
            expected[docs / "views" / directory / value / "_index.md"] = _leaf_page(
                f"{title}: {term.label}",
                f"Canonical taxonomy value `{value}` ({singular}).",
                records,
            )

    by_source: dict[str, list[ResearchRecord]] = {}
    by_status: dict[str, list[ResearchRecord]] = {}
    for record in corpus.records.values():
        by_status.setdefault(record.status, []).append(record)
        for source_id in record.source_ids():
            by_source.setdefault(source_id, []).append(record)
    expected[docs / "views" / "by-source" / "_index.md"] = _source_index(
        corpus, by_source
    )
    for source_id, records in by_source.items():
        source = corpus.sources[source_id]
        expected[docs / "views" / "by-source" / source_id / "_index.md"] = _leaf_page(
            f"By source: {source.name}",
            f"Records citing `{source_id}@{source.revision.key()}` or an older explicitly "
            "retained revision.",
            records,
        )
    expected[docs / "views" / "by-status" / "_index.md"] = _status_index(by_status)
    for status, records in by_status.items():
        expected[docs / "views" / "by-status" / status / "_index.md"] = _leaf_page(
            f"By status: {status}",
            "This is author-declared lifecycle state; inspect derived health on each record.",
            records,
        )
    return expected


def _assert_safe_projection_path(corpus: Corpus, path: Path) -> None:
    assert_no_redirecting_ancestors(corpus.paths.docs, purpose="generated-view path")
    assert_plain_contained_path(
        corpus.paths.docs, path, purpose="generated-view path"
    )


def _atomic_write_text(path: Path, content: str) -> None:
    handle, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.lexists(temporary):
            temporary.unlink()


def _existing_generated_files(corpus: Corpus) -> set[Path]:
    files: set[Path] = set()
    records_index = corpus.paths.records / "_index.md"
    _assert_safe_projection_path(corpus, records_index)
    if os.path.lexists(records_index):
        files.add(records_index)
    views = corpus.paths.docs / "views"
    _assert_safe_projection_path(corpus, views)
    if os.path.lexists(views):
        for directory, names, filenames in os.walk(views, topdown=True, followlinks=False):
            parent = Path(directory)
            _assert_safe_projection_path(corpus, parent)
            for name in names:
                _assert_safe_projection_path(corpus, parent / name)
            for name in filenames:
                path = parent / name
                _assert_safe_projection_path(corpus, path)
                files.add(path)
    return files


def render_views(corpus: Corpus, *, check: bool = False) -> tuple[Path, ...]:
    expected = expected_views(corpus)
    existing = _existing_generated_files(corpus)
    unexpected = sorted(existing - set(expected), key=lambda item: item.as_posix())
    # Records are authored, but their provenance block is generated from front
    # matter, so it is maintained here with the projections rather than trusted
    # to an author who cannot see the rendered page.
    provenance = expected_record_provenance(corpus)
    changed: list[Path] = list(provenance)

    for path in expected:
        _assert_safe_projection_path(corpus, path)

    for path in sorted(existing, key=lambda item: item.as_posix()):
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise CorpusError(f"cannot inspect generated view {path}: {exc}") from exc
        if GENERATED_MARKER not in text:
            raise CorpusError(
                f"refusing to replace non-generated file under research views: {path}"
            )

    # Validate the complete write set before touching either generated blocks
    # inside records or generated pages. A user-authored collision is a refusal
    # with zero mutation, not a partially completed rendering operation.
    for path in (*expected, *provenance):
        for parent in path.parents:
            if parent == corpus.paths.docs.parent:
                break
            if os.path.lexists(parent) and not parent.is_dir():
                raise CorpusError(f"projection parent is not a directory: {parent}")
        if os.path.lexists(path) and not path.is_file():
            raise CorpusError(f"projection target is not a file: {path}")
    fresh = load_corpus(corpus.paths)
    if fresh.input_hash != corpus.input_hash:
        raise CorpusError("canonical research inputs changed before rendering; try again")

    if not check:
        for path, content in provenance.items():
            _assert_safe_projection_path(corpus, path)
            _atomic_write_text(path, content)

    for path, content in sorted(expected.items(), key=lambda item: item[0].as_posix()):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                _assert_safe_projection_path(corpus, path)
                _atomic_write_text(path, content)

    for path in unexpected:
        changed.append(path)
        if not check:
            path.unlink()

    if not check:
        views = corpus.paths.docs / "views"
        if views.exists():
            for directory, _, _ in os.walk(views, topdown=False):
                path = Path(directory)
                if path != views:
                    try:
                        path.rmdir()
                    except OSError:
                        pass
    return tuple(sorted(set(changed), key=lambda item: item.as_posix()))
